version: '3'

tasks:

  cecil:start:
    desc: Start Cecil local server and watcher.
    cmds:
      - php cecil.phar serve
    aliases: [start]

  cecil:build:
    desc: Builds the website.
    cmds:
      - docker compose run node npm run build-dev
      - php cecil.phar build
    aliases: [build]

  deploy:production:
    cmds:
      - docker compose run node npm run build-prod
      - php cecil.phar build
      - rsync -atvPI ./_site/ xxx:/opt/blch-web-prd/web
    aliases: [deploy]